### PR TITLE
Fixed sentence onclick not being removed.

### LINKED ISSUE #125: OnClick events on each sentence aren't removed when turn app off
This is in content_script.js, removeSentenceEventListeners; not sure why not working

### PR DESCRIPTION
**Pull request by sjonany**

### CODE REVIEW

**Comment by sjonany** [comment]
Notes from my previous findings.
1. The code doing the remove() has to be the exact same context that installed the clickers. That's why I do message passing from  background to the same context that did the setup, as opposed to rerunning the content script.
2. This is more unclear why. But I had to cache these $("sdfasdf") lookups to the same set of variables, or else for some reason the click handlers are not found in subsequent calls anymore.

**Comment by sjonany** [comment]
Hold up, not submitting yet.
For some reason after this small change, the onclick "on" no longer works for some sentences.
Huh?? very confused. Debugging.

**Comment by sjonany** [comment]
Tested after the most recent markRanges fix. No more strange behavior! Ready for review.

**Review by benfrancis314 — APPROVED** [review]
LGTM

**Pull request merged**
