### PR TITLE
Loading

### PR DESCRIPTION
**Pull request by benfrancis314**
Loading animation, plus made close button a little different. Note that the setupLoadingIcon and removeLoadingIcon functions will have to be adjusted when we change the turnon method, but should just need to be moved.

### CODE REVIEW

**Comment by benfrancis314** [comment]
This is more of a demo than a real PR; this has the necessary functions for the loading, but we'll want to move them around when we change the turnon method later.

**Comment by benfrancis314** [comment]
So I'm NOT going to merge this.

**Comment by benfrancis314** [comment]
Also I had to build this off of a different branch than master bc master had that one bug, so the changes comparison is weird. So actually just wait and I can explain this to you in person

**Review by sjonany — APPROVED** [review]
Very nice!

**Comment by sjonany** [comment]
O just saw the rest of the comments LOL.
The changes in general look good. I'll wait off changing the setup / preproc flow til after this.

**Pull request closed without merging**
