### PR TITLE
On app install, redirect user to demo page, activate extension, show tutorial popup

### PR DESCRIPTION
**Pull request by sjonany**

### CODE REVIEW

**Comment by sjonany** [comment]
POPUP DIALOG IMPLEMENTATION
--------------------------------------------------------
So I'm not sure how video speed does it. 
image

This looks like a browser action popup, but from experimenting, and googling around, you CANNOT auto-open these extension popups.
https://developer.chrome.com/extensions/faq#faq-open-popups
So, I ended up opening a new window following https://stackoverflow.com/questions/10340481/popup-window-in-chrome-extension


OPENING WINDOW AND FOCUSING TO IT ON INSTALL
------------------------------------------
I followed https://www.gmass.co/blog/redirect-user-to-website-after-installing-chrome-extension/

**Comment by sjonany** [comment]
So, two undesirables here:

1. Idk how to do the popup like video speed controller. It's definitely not content script, which is injected to the webpage. That probably means it's an extension popup, but from googling around, and experimenting, I do NOT see how it can be auto-opened on install. https://developer.chrome.com/extensions/faq#faq-open-popups said it has to be user clicking it manually.
2. popup.html looks like poop.html

**Comment by sjonany** [comment]
Guesses: what other chrome stack can show this dialog? Chrome notifications? https://stackoverflow.com/questions/24965610/show-notifications-in-chrome-extension

I think we can launch w/ the dialog the way it is rn, and leave this additional prettification of [actual dialog, not window] as a separate nice-to-have item.

**Review by benfrancis314 — APPROVED** [review]
LGTM!

will play w the window part; also may be better to just use the function to inject html into the page

**Comment by sjonany** [comment]
OHHHHH video speed controller's message thing is a DEFAULT POST INSTALLATION message lol.
See this [SO post](https://stackoverflow.com/questions/51761769/change-default-text-in-the-popup-appearing-after-installation)

Also video speed controller is [open source](https://github.com/igrigorik/videospeed/search?q=%22use+this+extension+by+clicking+on+this+icon%22&unscoped_q=%22use+this+extension+by+clicking+on+this+icon%22), and I couldn't find the welcome message in the repo.

**Comment by benfrancis314** [comment]
ughhhhhhh

THANKS FOR FINDING THAT!!!!!

**Comment by benfrancis314** [comment]
... I don't recall seeing this when I installed it from the store though?

**Pull request merged**
