### PR TITLE
Generally fixed overlap of timer and instructions

### PR DESCRIPTION
**Pull request by benfrancis314**
This is fixed for me at a spectrum of different screen sizes, though eventually when make too short it runs into problems; at least on my computer, I think it is within the range of acceptability. But let me know if it works on your monitor and laptop

### CODE REVIEW

**Comment by sjonany** [comment]
image

**Comment by benfrancis314** [comment]
Damn, on mine it had that same problem but it had to be pretty short before it did so ... will figure out a more universal solution

**Comment by sjonany** [comment]
Tested wpm layout is good on both monitors.
Two new bugs only seen on laptop monitor:
1. Instruction text overflows
2. Instruction is cutoff at the bottom (altho i can still see all the content).

**Comment by benfrancis314** [comment]
Ah the tutorial pop up is also smooshed; will just try to make everything more flexible

**Comment by benfrancis314** [comment]
I'll make issues for them, good catch, I'll try to just make everything more flexible, which is a good design principle anyway

**Review by sjonany — APPROVED** [review]

**Comment by benfrancis314** [comment]
Going to close this one and PR a new one that actually fixes these problems

**Pull request closed without merging**
